-- AiCRM 数据库初始化脚本

-- 租户表
CREATE TABLE IF NOT EXISTS `tenant` (
  `id`                BIGINT       NOT NULL COMMENT '租户ID',
  `tenant_code`       VARCHAR(64)  NOT NULL COMMENT '租户编码',
  `tenant_name`       VARCHAR(128) NOT NULL COMMENT '租户名称',
  `logo_url`          VARCHAR(512) DEFAULT NULL,
  `contact_name`      VARCHAR(64)  DEFAULT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1 COMMENT '0禁用 1启用 2试用',
  `edition`           VARCHAR(32)  NOT NULL DEFAULT 'basic',
  `max_users`         INT          NOT NULL DEFAULT 10,
  `expire_date`       DATE         DEFAULT NULL,
  `storage_quota_mb`  BIGINT       NOT NULL DEFAULT 5120,
  `storage_used_mb`   BIGINT       NOT NULL DEFAULT 0,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 组织架构表
CREATE TABLE IF NOT EXISTS `organization` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `parent_id`         BIGINT       DEFAULT 0,
  `org_name`          VARCHAR(128) NOT NULL,
  `org_code`          VARCHAR(64)  DEFAULT NULL,
  `org_type`          TINYINT      NOT NULL DEFAULT 1 COMMENT '1公司 2部门 3团队',
  `org_path`          VARCHAR(512) NOT NULL,
  `leader_user_id`    BIGINT       DEFAULT NULL,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_parent` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 线索表
CREATE TABLE IF NOT EXISTS `lead` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `lead_no`           VARCHAR(32)  NOT NULL,
  `contact_name`      VARCHAR(64)  NOT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `company_name`      VARCHAR(256) DEFAULT NULL,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `source`            VARCHAR(32)  NOT NULL,
  `source_detail`     VARCHAR(256) DEFAULT NULL,
  `intention_level`   CHAR(1)      DEFAULT NULL,
  `lead_score`        INT          DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 0 COMMENT '0待分配 1已分配 2跟进中 3已转化 4已退回 5无效',
  `owner_user_id`     BIGINT       DEFAULT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `assign_user_id`    BIGINT       DEFAULT NULL,
  `assign_time`       DATETIME     DEFAULT NULL,
  `first_follow_time` DATETIME     DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `convert_time`      DATETIME     DEFAULT NULL,
  `convert_customer_id` BIGINT     DEFAULT NULL,
  `return_reason`     VARCHAR(512) DEFAULT NULL,
  `in_pool`           TINYINT(1)   NOT NULL DEFAULT 0,
  `pool_enter_time`   DATETIME     DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `remark`            TEXT         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_lead_no` (`tenant_id`, `lead_no`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 客户表
CREATE TABLE IF NOT EXISTS `customer` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_no`       VARCHAR(32)  NOT NULL,
  `customer_name`     VARCHAR(256) NOT NULL,
  `short_name`        VARCHAR(128) DEFAULT NULL,
  `customer_type`     TINYINT      NOT NULL DEFAULT 1 COMMENT '1企业 2个人',
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `scale`             VARCHAR(32)  DEFAULT NULL,
  `website`           VARCHAR(256) DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `district`          VARCHAR(32)  DEFAULT NULL,
  `address`           VARCHAR(512) DEFAULT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `lifecycle_stage`   TINYINT      NOT NULL DEFAULT 1 COMMENT '1潜在 2意向 3成交 4活跃 5VIP 6流失 7无效 8黑名单',
  `level`             CHAR(1)      DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `source_lead_id`    BIGINT       DEFAULT NULL,
  `source`            VARCHAR(32)  DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `next_follow_time`  DATETIME     DEFAULT NULL,
  `expected_purchase_date` DATE    DEFAULT NULL,
  `deal_amount`       DECIMAL(15,2) DEFAULT 0,
  `deal_count`        INT          NOT NULL DEFAULT 0,
  `erp_customer_id`   VARCHAR(64)  DEFAULT NULL,
  `erp_sync_status`   TINYINT      DEFAULT 0,
  `erp_last_sync_time` DATETIME   DEFAULT NULL,
  `approval_status`   TINYINT      DEFAULT 0,
  `remark`            TEXT         DEFAULT NULL,
  `tags`              VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_no` (`tenant_id`, `customer_no`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`),
  KEY `idx_tenant_stage` (`tenant_id`, `lifecycle_stage`),
  KEY `idx_tenant_name` (`tenant_id`, `customer_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 商机表
CREATE TABLE IF NOT EXISTS `opportunity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `opportunity_no`    VARCHAR(32)  NOT NULL,
  `opportunity_name`  VARCHAR(256) NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `stage_id`          BIGINT       NOT NULL,
  `expected_amount`   DECIMAL(15,2) DEFAULT NULL,
  `actual_amount`     DECIMAL(15,2) DEFAULT NULL,
  `win_rate`          INT          DEFAULT NULL,
  `expected_close_date` DATE       DEFAULT NULL,
  `actual_close_date` DATE         DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1 COMMENT '1进行中 2赢单 3输单 4无效',
  `loss_reason`       VARCHAR(512) DEFAULT NULL,
  `competitor`        VARCHAR(256) DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `remark`            TEXT         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_opp_no` (`tenant_id`, `opportunity_no`),
  KEY `idx_tenant_customer` (`tenant_id`, `customer_id`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 商机阶段配置表
CREATE TABLE IF NOT EXISTS `opportunity_stage_config` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `stage_name`        VARCHAR(64)  NOT NULL,
  `stage_code`        VARCHAR(32)  NOT NULL,
  `win_rate`          INT          NOT NULL DEFAULT 0,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `is_won`            TINYINT(1)   NOT NULL DEFAULT 0,
  `is_lost`           TINYINT(1)   NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 跟进记录表
CREATE TABLE IF NOT EXISTS `follow_up_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `biz_type`          TINYINT      NOT NULL COMMENT '1线索 2客户 3商机',
  `biz_id`            BIGINT       NOT NULL,
  `customer_id`       BIGINT       DEFAULT NULL,
  `follow_type`       TINYINT      NOT NULL COMMENT '1现场 2电话 3微信 4邮件 5企微 6其他',
  `content`           TEXT         NOT NULL,
  `visit_id`          BIGINT       DEFAULT NULL,
  `next_follow_time`  DATETIME     DEFAULT NULL,
  `next_follow_note`  VARCHAR(512) DEFAULT NULL,
  `has_recording`     TINYINT(1)   NOT NULL DEFAULT 0,
  `recording_file_id` BIGINT       DEFAULT NULL,
  `ai_summary`        TEXT         DEFAULT NULL,
  `ai_analysis`       TEXT         DEFAULT NULL,
  `has_violation`     TINYINT(1)   NOT NULL DEFAULT 0,
  `violation_detail`  TEXT         DEFAULT NULL,
  `follow_user_id`    BIGINT       NOT NULL,
  `follow_user_org_id` BIGINT     DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_biz` (`tenant_id`, `biz_type`, `biz_id`),
  KEY `idx_tenant_customer` (`tenant_id`, `customer_id`),
  KEY `idx_tenant_user` (`tenant_id`, `follow_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
