-- AiCRM 数据库初始化脚本

-- 租户表
CREATE TABLE IF NOT EXISTS `tenant` (
  `id`                BIGINT       NOT NULL COMMENT '租户ID',
  `tenant_code`       VARCHAR(64)  NOT NULL COMMENT '租户编码',
  `tenant_name`       VARCHAR(128) NOT NULL COMMENT '租户名称',
  `logo_url`          VARCHAR(512) DEFAULT NULL,
  `contact_name`      VARCHAR(64)  DEFAULT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1 COMMENT '0禁用 1启用 2试用',
  `edition`           VARCHAR(32)  NOT NULL DEFAULT 'basic',
  `max_users`         INT          NOT NULL DEFAULT 10,
  `expire_date`       DATE         DEFAULT NULL,
  `storage_quota_mb`  BIGINT       NOT NULL DEFAULT 5120,
  `storage_used_mb`   BIGINT       NOT NULL DEFAULT 0,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_code` (`tenant_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 组织架构表
CREATE TABLE IF NOT EXISTS `organization` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `parent_id`         BIGINT       DEFAULT 0,
  `org_name`          VARCHAR(128) NOT NULL,
  `org_code`          VARCHAR(64)  DEFAULT NULL,
  `org_type`          TINYINT      NOT NULL DEFAULT 1 COMMENT '1公司 2部门 3团队',
  `org_path`          VARCHAR(512) NOT NULL,
  `leader_user_id`    BIGINT       DEFAULT NULL,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_parent` (`tenant_id`, `parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 线索表
CREATE TABLE IF NOT EXISTS `lead` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `lead_no`           VARCHAR(32)  NOT NULL,
  `contact_name`      VARCHAR(64)  NOT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `company_name`      VARCHAR(256) DEFAULT NULL,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `source`            VARCHAR(32)  NOT NULL,
  `source_detail`     VARCHAR(256) DEFAULT NULL,
  `intention_level`   CHAR(1)      DEFAULT NULL,
  `lead_score`        INT          DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 0 COMMENT '0待分配 1已分配 2跟进中 3已转化 4已退回 5无效',
  `owner_user_id`     BIGINT       DEFAULT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `assign_user_id`    BIGINT       DEFAULT NULL,
  `assign_time`       DATETIME     DEFAULT NULL,
  `first_follow_time` DATETIME     DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `convert_time`      DATETIME     DEFAULT NULL,
  `convert_customer_id` BIGINT     DEFAULT NULL,
  `return_reason`     VARCHAR(512) DEFAULT NULL,
  `in_pool`           TINYINT(1)   NOT NULL DEFAULT 0,
  `pool_enter_time`   DATETIME     DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `remark`            TEXT         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_lead_no` (`tenant_id`, `lead_no`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 客户表
CREATE TABLE IF NOT EXISTS `customer` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_no`       VARCHAR(32)  NOT NULL,
  `customer_name`     VARCHAR(256) NOT NULL,
  `short_name`        VARCHAR(128) DEFAULT NULL,
  `customer_type`     TINYINT      NOT NULL DEFAULT 1 COMMENT '1企业 2个人',
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `scale`             VARCHAR(32)  DEFAULT NULL,
  `website`           VARCHAR(256) DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `district`          VARCHAR(32)  DEFAULT NULL,
  `address`           VARCHAR(512) DEFAULT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `lifecycle_stage`   TINYINT      NOT NULL DEFAULT 1 COMMENT '1潜在 2意向 3成交 4活跃 5VIP 6流失 7无效 8黑名单',
  `level`             CHAR(1)      DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `source_lead_id`    BIGINT       DEFAULT NULL,
  `source`            VARCHAR(32)  DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `next_follow_time`  DATETIME     DEFAULT NULL,
  `expected_purchase_date` DATE    DEFAULT NULL,
  `deal_amount`       DECIMAL(15,2) DEFAULT 0,
  `deal_count`        INT          NOT NULL DEFAULT 0,
  `erp_customer_id`   VARCHAR(64)  DEFAULT NULL,
  `erp_sync_status`   TINYINT      DEFAULT 0,
  `erp_last_sync_time` DATETIME   DEFAULT NULL,
  `approval_status`   TINYINT      DEFAULT 0,
  `remark`            TEXT         DEFAULT NULL,
  `tags`              VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_customer_no` (`tenant_id`, `customer_no`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`),
  KEY `idx_tenant_stage` (`tenant_id`, `lifecycle_stage`),
  KEY `idx_tenant_name` (`tenant_id`, `customer_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 商机表
CREATE TABLE IF NOT EXISTS `opportunity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `opportunity_no`    VARCHAR(32)  NOT NULL,
  `opportunity_name`  VARCHAR(256) NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `stage_id`          BIGINT       NOT NULL,
  `expected_amount`   DECIMAL(15,2) DEFAULT NULL,
  `actual_amount`     DECIMAL(15,2) DEFAULT NULL,
  `win_rate`          INT          DEFAULT NULL,
  `expected_close_date` DATE       DEFAULT NULL,
  `actual_close_date` DATE         DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1 COMMENT '1进行中 2赢单 3输单 4无效',
  `loss_reason`       VARCHAR(512) DEFAULT NULL,
  `competitor`        VARCHAR(256) DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `last_follow_time`  DATETIME     DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `remark`            TEXT         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_opp_no` (`tenant_id`, `opportunity_no`),
  KEY `idx_tenant_customer` (`tenant_id`, `customer_id`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`),
  KEY `idx_tenant_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 商机阶段配置表
CREATE TABLE IF NOT EXISTS `opportunity_stage_config` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `stage_name`        VARCHAR(64)  NOT NULL,
  `stage_code`        VARCHAR(32)  NOT NULL,
  `win_rate`          INT          NOT NULL DEFAULT 0,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `is_won`            TINYINT(1)   NOT NULL DEFAULT 0,
  `is_lost`           TINYINT(1)   NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 跟进记录表
CREATE TABLE IF NOT EXISTS `follow_up_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `biz_type`          TINYINT      NOT NULL COMMENT '1线索 2客户 3商机',
  `biz_id`            BIGINT       NOT NULL,
  `customer_id`       BIGINT       DEFAULT NULL,
  `follow_type`       TINYINT      NOT NULL COMMENT '1现场 2电话 3微信 4邮件 5企微 6其他',
  `content`           TEXT         NOT NULL,
  `visit_id`          BIGINT       DEFAULT NULL,
  `next_follow_time`  DATETIME     DEFAULT NULL,
  `next_follow_note`  VARCHAR(512) DEFAULT NULL,
  `has_recording`     TINYINT(1)   NOT NULL DEFAULT 0,
  `recording_file_id` BIGINT       DEFAULT NULL,
  `ai_summary`        TEXT         DEFAULT NULL,
  `ai_analysis`       TEXT         DEFAULT NULL,
  `has_violation`     TINYINT(1)   NOT NULL DEFAULT 0,
  `violation_detail`  TEXT         DEFAULT NULL,
  `follow_user_id`    BIGINT       NOT NULL,
  `follow_user_org_id` BIGINT     DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_biz` (`tenant_id`, `biz_type`, `biz_id`),
  KEY `idx_tenant_customer` (`tenant_id`, `customer_id`),
  KEY `idx_tenant_user` (`tenant_id`, `follow_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 活动表
CREATE TABLE IF NOT EXISTS `activity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `activity_no`       VARCHAR(32)  NOT NULL COMMENT '活动编号',
  `activity_name`     VARCHAR(256) NOT NULL COMMENT '活动名称',
  `activity_category` TINYINT      NOT NULL DEFAULT 1 COMMENT '1需要报名 2不需要报名',
  `activity_type`     TINYINT      NOT NULL COMMENT '1线下展会 2线上推广 3产品发布 4客户沙龙 5培训会议 6品牌宣传 7优惠活动 8内容分发 9其他',
  `description`       TEXT         DEFAULT NULL COMMENT '活动描述',
  `rich_content`      LONGTEXT    DEFAULT NULL COMMENT '富文本内容',
  `cover_image_url`   VARCHAR(1024) DEFAULT NULL COMMENT '封面图URL',
  `start_time`        DATETIME     NOT NULL COMMENT '开始时间',
  `end_time`          DATETIME     NOT NULL COMMENT '结束时间',
  `registration_start_time` DATETIME DEFAULT NULL COMMENT '报名开始时间',
  `registration_end_time`   DATETIME DEFAULT NULL COMMENT '报名截止时间',
  `max_participants`  INT          DEFAULT NULL COMMENT '最大参与人数',
  `current_participants` INT       NOT NULL DEFAULT 0 COMMENT '当前参与人数',
  `registration_approval` TINYINT  NOT NULL DEFAULT 0 COMMENT '0自动通过 1需审核',
  `registration_notice`  TEXT      DEFAULT NULL COMMENT '报名须知',
  `waitlist_enabled`  TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否启用候补',
  `location`          VARCHAR(512) DEFAULT NULL COMMENT '活动地点',
  `longitude`         DECIMAL(10,7) DEFAULT NULL COMMENT '经度',
  `latitude`          DECIMAL(10,7) DEFAULT NULL COMMENT '纬度',
  `online_url`        VARCHAR(1024) DEFAULT NULL COMMENT '线上活动URL',
  `qr_code_url`       VARCHAR(1024) DEFAULT NULL COMMENT '二维码图片URL',
  `qr_code_content`   VARCHAR(512) DEFAULT NULL COMMENT '二维码内容',
  `total_scans`       INT          NOT NULL DEFAULT 0 COMMENT '总扫码次数',
  `unique_scans`      INT          NOT NULL DEFAULT 0 COMMENT '独立扫码人数',
  `status`            TINYINT      NOT NULL DEFAULT 0 COMMENT '0草稿 1未开始 2报名中 3报名截止 4进行中 5已结束 6已取消',
  `owner_user_id`     BIGINT       DEFAULT NULL COMMENT '负责人用户ID',
  `owner_org_id`      BIGINT       DEFAULT NULL COMMENT '负责人组织ID',
  `budget`            DECIMAL(15,2) DEFAULT NULL COMMENT '预算',
  `actual_cost`       DECIMAL(15,2) DEFAULT NULL COMMENT '实际成本',
  `wechat_work_bind`  TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '企微绑定',
  `wechat_work_qr_url` VARCHAR(1024) DEFAULT NULL COMMENT '企微二维码URL',
  `remark`            TEXT         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tenant_activity_no` (`tenant_id`, `activity_no`),
  KEY `idx_tenant_category` (`tenant_id`, `activity_category`),
  KEY `idx_tenant_status` (`tenant_id`, `status`),
  KEY `idx_tenant_time` (`tenant_id`, `start_time`),
  KEY `idx_tenant_owner` (`tenant_id`, `owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动表';

-- 活动参与人表
CREATE TABLE IF NOT EXISTS `activity_participant` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `activity_id`       BIGINT       NOT NULL COMMENT '活动ID',
  `participant_name`  VARCHAR(64)  NOT NULL COMMENT '参与人姓名',
  `participant_phone` VARCHAR(32)  DEFAULT NULL COMMENT '参与人电话',
  `participant_email` VARCHAR(128) DEFAULT NULL COMMENT '参与人邮箱',
  `company_name`      VARCHAR(256) DEFAULT NULL COMMENT '公司名称',
  `position`          VARCHAR(64)  DEFAULT NULL COMMENT '职位',
  `source`            TINYINT      NOT NULL DEFAULT 1 COMMENT '1扫码报名 2手动录入 3批量导入 4扫码参与',
  `scan_time`         DATETIME     DEFAULT NULL COMMENT '扫码时间',
  `registration_status` TINYINT   NOT NULL DEFAULT 1 COMMENT '0待审核 1已通过 2已拒绝 3已取消 4候补',
  `registration_time` DATETIME     DEFAULT NULL COMMENT '报名时间',
  `reject_reason`     VARCHAR(512) DEFAULT NULL COMMENT '拒绝原因',
  `checkin_status`    TINYINT      NOT NULL DEFAULT 0 COMMENT '0未签到 1已签到',
  `checkin_time`      DATETIME     DEFAULT NULL COMMENT '签到时间',
  `is_customer`       TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否客户',
  `customer_id`       BIGINT       DEFAULT NULL COMMENT '客户ID',
  `is_lead`           TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否线索',
  `lead_id`           BIGINT       DEFAULT NULL COMMENT '线索ID',
  `friend_added`      TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否加好友',
  `friend_id`         BIGINT       DEFAULT NULL COMMENT '好友ID',
  `wechat_added`      TINYINT(1)   NOT NULL DEFAULT 0 COMMENT '是否加微信',
  `feedback`          TEXT         DEFAULT NULL COMMENT '反馈内容',
  `feedback_score`    TINYINT      DEFAULT NULL COMMENT '反馈评分1~5',
  `remark`            VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`           TINYINT(1)   NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_activity` (`tenant_id`, `activity_id`),
  KEY `idx_activity_reg_status` (`tenant_id`, `activity_id`, `registration_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='活动参与人表';

-- 好友表
CREATE TABLE IF NOT EXISTS `friend` (
  `id`                    BIGINT       NOT NULL,
  `tenant_id`             BIGINT       NOT NULL,
  `user_id`               BIGINT       DEFAULT NULL COMMENT '销售员用户ID',
  `friend_name`           VARCHAR(64)  NOT NULL COMMENT '好友姓名',
  `friend_phone`          VARCHAR(32)  DEFAULT NULL COMMENT '好友手机号',
  `friend_avatar_url`     VARCHAR(512) DEFAULT NULL COMMENT '好友头像URL',
  `friend_company`        VARCHAR(256) DEFAULT NULL COMMENT '好友公司',
  `friend_position`       VARCHAR(64)  DEFAULT NULL COMMENT '好友职位',
  `friend_type`           TINYINT      NOT NULL DEFAULT 1 COMMENT '1平台 2企微 3双渠道',
  `source`                TINYINT      NOT NULL DEFAULT 3 COMMENT '1活动扫码 2企微同步 3手动添加 4线索导入 5名片扫描',
  `source_activity_id`    BIGINT       DEFAULT NULL COMMENT '来源活动ID',
  `wechat_external_userid` VARCHAR(128) DEFAULT NULL COMMENT '企微外部联系人ID',
  `wechat_unionid`        VARCHAR(128) DEFAULT NULL COMMENT '企微UnionID',
  `wechat_nickname`       VARCHAR(128) DEFAULT NULL COMMENT '企微昵称',
  `customer_id`           BIGINT       DEFAULT NULL COMMENT '关联客户ID',
  `contact_id`            BIGINT       DEFAULT NULL COMMENT '关联联系人ID',
  `lead_id`               BIGINT       DEFAULT NULL COMMENT '关联线索ID',
  `status`                TINYINT      NOT NULL DEFAULT 1 COMMENT '1正常 2已删除 3已被删 4已拉黑',
  `tags`                  VARCHAR(512) DEFAULT NULL COMMENT '标签',
  `remark`                TEXT         DEFAULT NULL COMMENT '备注',
  `add_time`              DATETIME     DEFAULT NULL COMMENT '添加时间',
  `last_chat_time`        DATETIME     DEFAULT NULL COMMENT '最后聊天时间',
  `created_by`            BIGINT       DEFAULT NULL,
  `created_time`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`            BIGINT       DEFAULT NULL,
  `updated_time`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted`               TINYINT      NOT NULL DEFAULT 0,
  `version`               INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_tenant_user` (`tenant_id`, `user_id`),
  KEY `idx_tenant_friend_type` (`tenant_id`, `friend_type`),
  KEY `idx_tenant_source` (`tenant_id`, `source`),
  KEY `idx_tenant_customer` (`tenant_id`, `customer_id`),
  KEY `idx_tenant_add_time` (`tenant_id`, `add_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='好友表';
