-- H2 兼容 schema（测试用）

CREATE TABLE IF NOT EXISTS `tenant` (
  `id`                BIGINT       NOT NULL,
  `tenant_code`       VARCHAR(64)  NOT NULL,
  `tenant_name`       VARCHAR(128) NOT NULL,
  `logo_url`          VARCHAR(512) DEFAULT NULL,
  `contact_name`      VARCHAR(64)  DEFAULT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `edition`           VARCHAR(32)  NOT NULL DEFAULT 'basic',
  `max_users`         INT          NOT NULL DEFAULT 10,
  `expire_date`       DATE         DEFAULT NULL,
  `storage_quota_mb`  BIGINT       NOT NULL DEFAULT 5120,
  `storage_used_mb`   BIGINT       NOT NULL DEFAULT 0,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `organization` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `parent_id`         BIGINT       DEFAULT 0,
  `org_name`          VARCHAR(128) NOT NULL,
  `org_code`          VARCHAR(64)  DEFAULT NULL,
  `org_type`          TINYINT      NOT NULL DEFAULT 1,
  `org_path`          VARCHAR(512) NOT NULL,
  `leader_user_id`    BIGINT       DEFAULT NULL,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `lead` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `lead_no`           VARCHAR(32)  NOT NULL,
  `contact_name`      VARCHAR(64)  NOT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `company_name`      VARCHAR(256) DEFAULT NULL,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `source`            VARCHAR(32)  NOT NULL,
  `source_detail`     VARCHAR(256) DEFAULT NULL,
  `intention_level`   CHAR(1)      DEFAULT NULL,
  `lead_score`        INT          DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 0,
  `owner_user_id`     BIGINT       DEFAULT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `assign_user_id`    BIGINT       DEFAULT NULL,
  `assign_time`       TIMESTAMP    DEFAULT NULL,
  `first_follow_time` TIMESTAMP    DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `convert_time`      TIMESTAMP    DEFAULT NULL,
  `convert_customer_id` BIGINT     DEFAULT NULL,
  `return_reason`     VARCHAR(512) DEFAULT NULL,
  `in_pool`           TINYINT      NOT NULL DEFAULT 0,
  `pool_enter_time`   TIMESTAMP    DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `customer` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_no`       VARCHAR(32)  NOT NULL,
  `customer_name`     VARCHAR(256) NOT NULL,
  `short_name`        VARCHAR(128) DEFAULT NULL,
  `customer_type`     TINYINT      NOT NULL DEFAULT 1,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `scale`             VARCHAR(32)  DEFAULT NULL,
  `website`           VARCHAR(256) DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `district`          VARCHAR(32)  DEFAULT NULL,
  `address`           VARCHAR(512) DEFAULT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `lifecycle_stage`   TINYINT      NOT NULL DEFAULT 1,
  `level`             CHAR(1)      DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `source_lead_id`    BIGINT       DEFAULT NULL,
  `source`            VARCHAR(32)  DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `next_follow_time`  TIMESTAMP    DEFAULT NULL,
  `expected_purchase_date` DATE    DEFAULT NULL,
  `deal_amount`       DECIMAL(15,2) DEFAULT 0,
  `deal_count`        INT          NOT NULL DEFAULT 0,
  `erp_customer_id`   VARCHAR(64)  DEFAULT NULL,
  `erp_sync_status`   TINYINT      DEFAULT 0,
  `erp_last_sync_time` TIMESTAMP  DEFAULT NULL,
  `approval_status`   TINYINT      DEFAULT 0,
  `remark`            CLOB         DEFAULT NULL,
  `tags`              VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `opportunity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `opportunity_no`    VARCHAR(32)  NOT NULL,
  `opportunity_name`  VARCHAR(256) NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `stage_id`          BIGINT       NOT NULL,
  `expected_amount`   DECIMAL(15,2) DEFAULT NULL,
  `actual_amount`     DECIMAL(15,2) DEFAULT NULL,
  `win_rate`          INT          DEFAULT NULL,
  `expected_close_date` DATE       DEFAULT NULL,
  `actual_close_date` DATE         DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `loss_reason`       VARCHAR(512) DEFAULT NULL,
  `competitor`        VARCHAR(256) DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `opportunity_stage_config` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `stage_name`        VARCHAR(64)  NOT NULL,
  `stage_code`        VARCHAR(32)  NOT NULL,
  `win_rate`          INT          NOT NULL DEFAULT 0,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `is_won`            TINYINT      NOT NULL DEFAULT 0,
  `is_lost`           TINYINT      NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `follow_up_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `biz_type`          TINYINT      NOT NULL,
  `biz_id`            BIGINT       NOT NULL,
  `customer_id`       BIGINT       DEFAULT NULL,
  `follow_type`       TINYINT      NOT NULL,
  `content`           CLOB         NOT NULL,
  `visit_id`          BIGINT       DEFAULT NULL,
  `next_follow_time`  TIMESTAMP    DEFAULT NULL,
  `next_follow_note`  VARCHAR(512) DEFAULT NULL,
  `has_recording`     TINYINT      NOT NULL DEFAULT 0,
  `recording_file_id` BIGINT       DEFAULT NULL,
  `ai_summary`        CLOB         DEFAULT NULL,
  `ai_analysis`       CLOB         DEFAULT NULL,
  `has_violation`     TINYINT      NOT NULL DEFAULT 0,
  `violation_detail`  CLOB         DEFAULT NULL,
  `follow_user_id`    BIGINT       NOT NULL,
  `follow_user_org_id` BIGINT     DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `activity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `activity_no`       VARCHAR(32)  NOT NULL,
  `activity_name`     VARCHAR(256) NOT NULL,
  `activity_category` TINYINT      NOT NULL DEFAULT 1,
  `activity_type`     TINYINT      NOT NULL,
  `description`       CLOB         DEFAULT NULL,
  `rich_content`      CLOB         DEFAULT NULL,
  `cover_image_url`   VARCHAR(1024) DEFAULT NULL,
  `start_time`        TIMESTAMP    NOT NULL,
  `end_time`          TIMESTAMP    NOT NULL,
  `registration_start_time` TIMESTAMP DEFAULT NULL,
  `registration_end_time`   TIMESTAMP DEFAULT NULL,
  `max_participants`  INT          DEFAULT NULL,
  `current_participants` INT       NOT NULL DEFAULT 0,
  `registration_approval` TINYINT  NOT NULL DEFAULT 0,
  `registration_notice`  CLOB     DEFAULT NULL,
  `waitlist_enabled`  TINYINT      NOT NULL DEFAULT 0,
  `location`          VARCHAR(512) DEFAULT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `online_url`        VARCHAR(1024) DEFAULT NULL,
  `qr_code_url`       VARCHAR(1024) DEFAULT NULL,
  `qr_code_content`   VARCHAR(512) DEFAULT NULL,
  `total_scans`       INT          NOT NULL DEFAULT 0,
  `unique_scans`      INT          NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 0,
  `owner_user_id`     BIGINT       DEFAULT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `budget`            DECIMAL(15,2) DEFAULT NULL,
  `actual_cost`       DECIMAL(15,2) DEFAULT NULL,
  `wechat_work_bind`  TINYINT      NOT NULL DEFAULT 0,
  `wechat_work_qr_url` VARCHAR(1024) DEFAULT NULL,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `activity_participant` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `activity_id`       BIGINT       NOT NULL,
  `participant_name`  VARCHAR(64)  NOT NULL,
  `participant_phone`  VARCHAR(32)  DEFAULT NULL,
  `participant_email` VARCHAR(128) DEFAULT NULL,
  `company_name`      VARCHAR(256) DEFAULT NULL,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `source`            TINYINT      NOT NULL DEFAULT 1,
  `scan_time`         TIMESTAMP    DEFAULT NULL,
  `registration_status` TINYINT   NOT NULL DEFAULT 1,
  `registration_time` TIMESTAMP   DEFAULT NULL,
  `reject_reason`     VARCHAR(512) DEFAULT NULL,
  `checkin_status`    TINYINT      NOT NULL DEFAULT 0,
  `checkin_time`      TIMESTAMP    DEFAULT NULL,
  `is_customer`       TINYINT      NOT NULL DEFAULT 0,
  `customer_id`       BIGINT       DEFAULT NULL,
  `is_lead`           TINYINT      NOT NULL DEFAULT 0,
  `lead_id`           BIGINT       DEFAULT NULL,
  `friend_added`      TINYINT      NOT NULL DEFAULT 0,
  `friend_id`         BIGINT       DEFAULT NULL,
  `wechat_added`      TINYINT      NOT NULL DEFAULT 0,
  `feedback`          CLOB         DEFAULT NULL,
  `feedback_score`    TINYINT      DEFAULT NULL,
  `remark`            VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `friend` (
  `id`                    BIGINT       NOT NULL,
  `tenant_id`             BIGINT       NOT NULL,
  `user_id`               BIGINT       DEFAULT NULL,
  `friend_name`           VARCHAR(64)  NOT NULL,
  `friend_phone`          VARCHAR(32)  DEFAULT NULL,
  `friend_avatar_url`     VARCHAR(512) DEFAULT NULL,
  `friend_company`        VARCHAR(256) DEFAULT NULL,
  `friend_position`       VARCHAR(64)  DEFAULT NULL,
  `friend_type`           TINYINT      NOT NULL DEFAULT 1,
  `source`                TINYINT      NOT NULL DEFAULT 3,
  `source_activity_id`    BIGINT       DEFAULT NULL,
  `wechat_external_userid` VARCHAR(128) DEFAULT NULL,
  `wechat_unionid`        VARCHAR(128) DEFAULT NULL,
  `wechat_nickname`       VARCHAR(128) DEFAULT NULL,
  `customer_id`           BIGINT       DEFAULT NULL,
  `contact_id`            BIGINT       DEFAULT NULL,
  `lead_id`               BIGINT       DEFAULT NULL,
  `status`                TINYINT      NOT NULL DEFAULT 1,
  `tags`                  VARCHAR(512) DEFAULT NULL,
  `remark`                CLOB         DEFAULT NULL,
  `add_time`              TIMESTAMP    DEFAULT NULL,
  `last_chat_time`        TIMESTAMP    DEFAULT NULL,
  `created_by`            BIGINT       DEFAULT NULL,
  `created_time`          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`            BIGINT       DEFAULT NULL,
  `updated_time`          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`               TINYINT      NOT NULL DEFAULT 0,
  `version`               INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `visit_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `visit_no`          VARCHAR(32)  NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `visit_type`        TINYINT      NOT NULL,
  `visit_purpose`     VARCHAR(512) DEFAULT NULL,
  `visit_result`      CLOB         DEFAULT NULL,
  `visit_time`        TIMESTAMP    DEFAULT NULL,
  `visit_end_time`    TIMESTAMP    DEFAULT NULL,
  `visit_duration`    INT          DEFAULT NULL,
  `checkin_address`   VARCHAR(512) DEFAULT NULL,
  `checkin_longitude` DECIMAL(10,7) DEFAULT NULL,
  `checkin_latitude`  DECIMAL(10,7) DEFAULT NULL,
  `checkin_time`      TIMESTAMP    DEFAULT NULL,
  `checkin_photo_url` VARCHAR(512) DEFAULT NULL,
  `checkout_time`     TIMESTAMP    DEFAULT NULL,
  `call_phone`        VARCHAR(32)  DEFAULT NULL,
  `call_duration`    INT          DEFAULT NULL,
  `recording_file_id` BIGINT       DEFAULT NULL,
  `recording_url`     VARCHAR(512) DEFAULT NULL,
  `ai_summary`        CLOB         DEFAULT NULL,
  `has_violation`     TINYINT      NOT NULL DEFAULT 0,
  `chat_screenshot_urls` CLOB      DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `visitor_user_id`   BIGINT       DEFAULT NULL,
  `visitor_org_id`    BIGINT       DEFAULT NULL,
  `follow_up_id`      BIGINT       DEFAULT NULL,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `checkin_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `user_id`           BIGINT       NOT NULL,
  `checkin_type`      TINYINT      NOT NULL,
  `checkin_time`      TIMESTAMP    NOT NULL,
  `address`           VARCHAR(512) NOT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `photo_url`         VARCHAR(512) DEFAULT NULL,
  `wifi_name`         VARCHAR(128) DEFAULT NULL,
  `device_info`       VARCHAR(256) DEFAULT NULL,
  `related_visit_id`  BIGINT       DEFAULT NULL,
  `remark`            VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `location_report` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `user_id`           BIGINT       NOT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `accuracy`          FLOAT        DEFAULT NULL,
  `address`           VARCHAR(512) DEFAULT NULL,
  `report_time`       TIMESTAMP    NOT NULL,
  `report_type`       TINYINT      DEFAULT NULL,
  `related_biz_type` VARCHAR(64)  DEFAULT NULL,
  `related_biz_id`    BIGINT       DEFAULT NULL,
  `battery_level`     INT          DEFAULT NULL,
  `network_type`      VARCHAR(32)  DEFAULT NULL,
  `device_info`       VARCHAR(256) DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `work_task` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `task_no`           VARCHAR(32)  NOT NULL,
  `task_title`        VARCHAR(256) NOT NULL,
  `task_content`      CLOB         DEFAULT NULL,
  `task_type`         TINYINT      NOT NULL,
  `priority`          TINYINT      DEFAULT 2,
  `status`            TINYINT      NOT NULL DEFAULT 0,
  `plan_start_time`   TIMESTAMP    DEFAULT NULL,
  `plan_end_time`     TIMESTAMP    DEFAULT NULL,
  `actual_start_time` TIMESTAMP    DEFAULT NULL,
  `actual_end_time`   TIMESTAMP    DEFAULT NULL,
  `completion_note`   CLOB         DEFAULT NULL,
  `completion_rate`   INT          DEFAULT NULL,
  `assign_type`       TINYINT      DEFAULT NULL,
  `assignee_user_id`  BIGINT       NOT NULL,
  `assigner_user_id`  BIGINT       DEFAULT NULL,
  `related_biz_type`  TINYINT      DEFAULT NULL,
  `related_biz_id`    BIGINT       DEFAULT NULL,
  `related_visit_id`  BIGINT       DEFAULT NULL,
  `remind_time`       TIMESTAMP    DEFAULT NULL,
  `is_reminded`       TINYINT      NOT NULL DEFAULT 0,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `third_party_config` (
  `id` BIGINT NOT NULL, `tenant_id` BIGINT NOT NULL,
  `provider` VARCHAR(32) NOT NULL, `api_base_url` VARCHAR(512) DEFAULT NULL,
  `app_key` VARCHAR(256) DEFAULT NULL, `app_secret` VARCHAR(256) DEFAULT NULL,
  `daily_quota` INT NOT NULL DEFAULT 100, `daily_used` INT NOT NULL DEFAULT 0,
  `contact_daily_quota` INT NOT NULL DEFAULT 50, `contact_daily_used` INT NOT NULL DEFAULT 0,
  `contact_monthly_quota` INT DEFAULT NULL, `contact_monthly_used` INT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` BIGINT DEFAULT NULL, `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT DEFAULT NULL, `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0, `version` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `enterprise_query_cache` (
  `id` BIGINT NOT NULL, `tenant_id` BIGINT NOT NULL,
  `company_name` VARCHAR(256) NOT NULL, `credit_code` VARCHAR(32) DEFAULT NULL,
  `legal_person` VARCHAR(64) DEFAULT NULL, `registered_capital` VARCHAR(64) DEFAULT NULL,
  `established_date` DATE DEFAULT NULL, `company_status` VARCHAR(32) DEFAULT NULL,
  `company_type` VARCHAR(64) DEFAULT NULL, `industry` VARCHAR(128) DEFAULT NULL,
  `province` VARCHAR(32) DEFAULT NULL, `city` VARCHAR(32) DEFAULT NULL,
  `address` VARCHAR(512) DEFAULT NULL, `business_scope` CLOB DEFAULT NULL,
  `contact_phone` VARCHAR(64) DEFAULT NULL, `contact_email` VARCHAR(128) DEFAULT NULL,
  `website` VARCHAR(256) DEFAULT NULL, `source` VARCHAR(32) NOT NULL DEFAULT 'wdyl',
  `is_platform_customer` TINYINT NOT NULL DEFAULT 0, `matched_customer_id` BIGINT DEFAULT NULL,
  `query_time` TIMESTAMP NOT NULL, `expire_time` TIMESTAMP NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `enterprise_contact` (
  `id` BIGINT NOT NULL, `tenant_id` BIGINT NOT NULL,
  `credit_code` VARCHAR(32) NOT NULL, `company_name` VARCHAR(256) NOT NULL,
  `contact_name` VARCHAR(64) DEFAULT NULL, `position` VARCHAR(128) DEFAULT NULL,
  `department` VARCHAR(128) DEFAULT NULL, `phone` VARCHAR(32) DEFAULT NULL,
  `telephone` VARCHAR(64) DEFAULT NULL, `email` VARCHAR(256) DEFAULT NULL,
  `source` VARCHAR(32) NOT NULL DEFAULT 'wdyl', `source_type` VARCHAR(32) DEFAULT NULL,
  `reliability` TINYINT DEFAULT NULL, `is_imported` TINYINT NOT NULL DEFAULT 0,
  `imported_customer_id` BIGINT DEFAULT NULL, `imported_contact_id` BIGINT DEFAULT NULL,
  `query_user_id` BIGINT NOT NULL, `query_time` TIMESTAMP NOT NULL,
  `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `customer_blacklist` (
  `id` BIGINT NOT NULL, `tenant_id` BIGINT NOT NULL,
  `customer_id` BIGINT DEFAULT NULL, `company_name` VARCHAR(256) NOT NULL,
  `credit_code` VARCHAR(32) DEFAULT NULL, `contact_phone` VARCHAR(32) DEFAULT NULL,
  `blacklist_type` TINYINT NOT NULL, `reason` CLOB NOT NULL,
  `evidence_urls` CLOB DEFAULT NULL, `status` TINYINT NOT NULL DEFAULT 1,
  `operated_by` BIGINT NOT NULL, `release_by` BIGINT DEFAULT NULL,
  `release_time` TIMESTAMP DEFAULT NULL, `release_reason` VARCHAR(512) DEFAULT NULL,
  `created_by` BIGINT DEFAULT NULL, `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT DEFAULT NULL, `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0, `version` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `call_recording` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `user_id`           BIGINT       DEFAULT NULL,
  `customer_id`       BIGINT       DEFAULT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `visit_id`          BIGINT       DEFAULT NULL,
  `call_type`         TINYINT      DEFAULT NULL,
  `caller_number`     VARCHAR(32)  DEFAULT NULL,
  `callee_number`     VARCHAR(32)  DEFAULT NULL,
  `call_start_time`   TIMESTAMP    DEFAULT NULL,
  `call_end_time`     TIMESTAMP    DEFAULT NULL,
  `call_duration`     INT          DEFAULT NULL,
  `recording_file_url` VARCHAR(512) DEFAULT NULL,
  `recording_file_size` BIGINT     DEFAULT NULL,
  `recording_format`  VARCHAR(32)  DEFAULT NULL,
  `transcription_status` TINYINT   DEFAULT 0,
  `transcription_text` CLOB       DEFAULT NULL,
  `ai_summary`        CLOB         DEFAULT NULL,
  `ai_keywords`       VARCHAR(512) DEFAULT NULL,
  `ai_sentiment`      VARCHAR(128) DEFAULT NULL,
  `violation_check_status` TINYINT DEFAULT 0,
  `has_violation`     TINYINT      NOT NULL DEFAULT 0,
  `violation_detail`  CLOB         DEFAULT NULL,
  `violation_level`   TINYINT      DEFAULT NULL,
  `source`            VARCHAR(64)  DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `violation_word` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `word`              VARCHAR(128) NOT NULL,
  `category`          VARCHAR(64)  DEFAULT NULL,
  `level`             TINYINT      NOT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `tenant_wechat_work_config` (
  `id` BIGINT NOT NULL, `tenant_id` BIGINT NOT NULL,
  `corp_id` VARCHAR(64) NOT NULL, `agent_id` VARCHAR(64) NOT NULL,
  `secret` VARCHAR(256) NOT NULL, `contact_secret` VARCHAR(256) DEFAULT NULL,
  `customer_secret` VARCHAR(256) DEFAULT NULL, `callback_token` VARCHAR(128) DEFAULT NULL,
  `callback_aes_key` VARCHAR(256) DEFAULT NULL, `contact_way_id` VARCHAR(64) DEFAULT NULL,
  `welcome_msg` VARCHAR(1024) DEFAULT NULL, `status` TINYINT NOT NULL DEFAULT 1,
  `created_by` BIGINT DEFAULT NULL, `created_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` BIGINT DEFAULT NULL, `updated_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0, `version` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `customer_contact` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_name`      VARCHAR(64)  NOT NULL,
  `gender`            TINYINT      DEFAULT 0,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `department`        VARCHAR(128) DEFAULT NULL,
  `phone`             VARCHAR(32)  DEFAULT NULL,
  `telephone`         VARCHAR(64)  DEFAULT NULL,
  `email`             VARCHAR(128) DEFAULT NULL,
  `wechat`            VARCHAR(64)  DEFAULT NULL,
  `is_primary`        TINYINT      DEFAULT 0,
  `is_decision_maker` TINYINT      DEFAULT 0,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `notification` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `user_id`           BIGINT       NOT NULL,
  `title`             VARCHAR(256) NOT NULL,
  `content`           CLOB         DEFAULT NULL,
  `msg_type`          TINYINT      NOT NULL,
  `biz_type`          VARCHAR(64)  DEFAULT NULL,
  `biz_id`            BIGINT       DEFAULT NULL,
  `is_read`           TINYINT      NOT NULL DEFAULT 0,
  `read_time`         TIMESTAMP    DEFAULT NULL,
  `push_channels`     VARCHAR(256) DEFAULT NULL,
  `push_status`       TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `customer_approval` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `approval_type`     TINYINT      NOT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `applicant_id`      BIGINT       DEFAULT NULL,
  `approver_id`       BIGINT       DEFAULT NULL,
  `approve_time`      TIMESTAMP    DEFAULT NULL,
  `approve_remark`    VARCHAR(512) DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `lead_assign_log` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `lead_id`           BIGINT       NOT NULL,
  `assign_type`       TINYINT      NOT NULL,
  `from_user_id`      BIGINT       DEFAULT NULL,
  `to_user_id`        BIGINT       DEFAULT NULL,
  `assign_by`         BIGINT       DEFAULT NULL,
  `remark`            VARCHAR(512) DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `lead_pool_config` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `pool_name`         VARCHAR(128) NOT NULL,
  `recycle_days`      INT          NOT NULL DEFAULT 7,
  `max_hold_count`    INT          NOT NULL DEFAULT 50,
  `daily_pick_limit`  INT          NOT NULL DEFAULT 5,
  `visible_org_ids`   VARCHAR(512) DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `opportunity_stage_log` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `opportunity_id`    BIGINT       NOT NULL,
  `from_stage_id`     BIGINT       DEFAULT NULL,
  `to_stage_id`       BIGINT       DEFAULT NULL,
  `stay_days`         INT          DEFAULT NULL,
  `remark`            VARCHAR(512) DEFAULT NULL,
  `operated_by`       BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);
