-- H2 兼容 schema（测试用）

CREATE TABLE IF NOT EXISTS `tenant` (
  `id`                BIGINT       NOT NULL,
  `tenant_code`       VARCHAR(64)  NOT NULL,
  `tenant_name`       VARCHAR(128) NOT NULL,
  `logo_url`          VARCHAR(512) DEFAULT NULL,
  `contact_name`      VARCHAR(64)  DEFAULT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `edition`           VARCHAR(32)  NOT NULL DEFAULT 'basic',
  `max_users`         INT          NOT NULL DEFAULT 10,
  `expire_date`       DATE         DEFAULT NULL,
  `storage_quota_mb`  BIGINT       NOT NULL DEFAULT 5120,
  `storage_used_mb`   BIGINT       NOT NULL DEFAULT 0,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `organization` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `parent_id`         BIGINT       DEFAULT 0,
  `org_name`          VARCHAR(128) NOT NULL,
  `org_code`          VARCHAR(64)  DEFAULT NULL,
  `org_type`          TINYINT      NOT NULL DEFAULT 1,
  `org_path`          VARCHAR(512) NOT NULL,
  `leader_user_id`    BIGINT       DEFAULT NULL,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `lead` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `lead_no`           VARCHAR(32)  NOT NULL,
  `contact_name`      VARCHAR(64)  NOT NULL,
  `contact_phone`     VARCHAR(32)  DEFAULT NULL,
  `contact_email`     VARCHAR(128) DEFAULT NULL,
  `company_name`      VARCHAR(256) DEFAULT NULL,
  `position`          VARCHAR(64)  DEFAULT NULL,
  `source`            VARCHAR(32)  NOT NULL,
  `source_detail`     VARCHAR(256) DEFAULT NULL,
  `intention_level`   CHAR(1)      DEFAULT NULL,
  `lead_score`        INT          DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 0,
  `owner_user_id`     BIGINT       DEFAULT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `assign_user_id`    BIGINT       DEFAULT NULL,
  `assign_time`       TIMESTAMP    DEFAULT NULL,
  `first_follow_time` TIMESTAMP    DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `convert_time`      TIMESTAMP    DEFAULT NULL,
  `convert_customer_id` BIGINT     DEFAULT NULL,
  `return_reason`     VARCHAR(512) DEFAULT NULL,
  `in_pool`           TINYINT      NOT NULL DEFAULT 0,
  `pool_enter_time`   TIMESTAMP    DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `customer` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `customer_no`       VARCHAR(32)  NOT NULL,
  `customer_name`     VARCHAR(256) NOT NULL,
  `short_name`        VARCHAR(128) DEFAULT NULL,
  `customer_type`     TINYINT      NOT NULL DEFAULT 1,
  `industry`          VARCHAR(64)  DEFAULT NULL,
  `scale`             VARCHAR(32)  DEFAULT NULL,
  `website`           VARCHAR(256) DEFAULT NULL,
  `province`          VARCHAR(32)  DEFAULT NULL,
  `city`              VARCHAR(32)  DEFAULT NULL,
  `district`          VARCHAR(32)  DEFAULT NULL,
  `address`           VARCHAR(512) DEFAULT NULL,
  `longitude`         DECIMAL(10,7) DEFAULT NULL,
  `latitude`          DECIMAL(10,7) DEFAULT NULL,
  `lifecycle_stage`   TINYINT      NOT NULL DEFAULT 1,
  `level`             CHAR(1)      DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `source_lead_id`    BIGINT       DEFAULT NULL,
  `source`            VARCHAR(32)  DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `next_follow_time`  TIMESTAMP    DEFAULT NULL,
  `expected_purchase_date` DATE    DEFAULT NULL,
  `deal_amount`       DECIMAL(15,2) DEFAULT 0,
  `deal_count`        INT          NOT NULL DEFAULT 0,
  `erp_customer_id`   VARCHAR(64)  DEFAULT NULL,
  `erp_sync_status`   TINYINT      DEFAULT 0,
  `erp_last_sync_time` TIMESTAMP  DEFAULT NULL,
  `approval_status`   TINYINT      DEFAULT 0,
  `remark`            CLOB         DEFAULT NULL,
  `tags`              VARCHAR(512) DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `opportunity` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `opportunity_no`    VARCHAR(32)  NOT NULL,
  `opportunity_name`  VARCHAR(256) NOT NULL,
  `customer_id`       BIGINT       NOT NULL,
  `contact_id`        BIGINT       DEFAULT NULL,
  `stage_id`          BIGINT       NOT NULL,
  `expected_amount`   DECIMAL(15,2) DEFAULT NULL,
  `actual_amount`     DECIMAL(15,2) DEFAULT NULL,
  `win_rate`          INT          DEFAULT NULL,
  `expected_close_date` DATE       DEFAULT NULL,
  `actual_close_date` DATE         DEFAULT NULL,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `loss_reason`       VARCHAR(512) DEFAULT NULL,
  `competitor`        VARCHAR(256) DEFAULT NULL,
  `owner_user_id`     BIGINT       NOT NULL,
  `owner_org_id`      BIGINT       DEFAULT NULL,
  `last_follow_time`  TIMESTAMP    DEFAULT NULL,
  `follow_count`      INT          NOT NULL DEFAULT 0,
  `remark`            CLOB         DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `opportunity_stage_config` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `stage_name`        VARCHAR(64)  NOT NULL,
  `stage_code`        VARCHAR(32)  NOT NULL,
  `win_rate`          INT          NOT NULL DEFAULT 0,
  `sort_order`        INT          NOT NULL DEFAULT 0,
  `is_won`            TINYINT      NOT NULL DEFAULT 0,
  `is_lost`           TINYINT      NOT NULL DEFAULT 0,
  `status`            TINYINT      NOT NULL DEFAULT 1,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `follow_up_record` (
  `id`                BIGINT       NOT NULL,
  `tenant_id`         BIGINT       NOT NULL,
  `biz_type`          TINYINT      NOT NULL,
  `biz_id`            BIGINT       NOT NULL,
  `customer_id`       BIGINT       DEFAULT NULL,
  `follow_type`       TINYINT      NOT NULL,
  `content`           CLOB         NOT NULL,
  `visit_id`          BIGINT       DEFAULT NULL,
  `next_follow_time`  TIMESTAMP    DEFAULT NULL,
  `next_follow_note`  VARCHAR(512) DEFAULT NULL,
  `has_recording`     TINYINT      NOT NULL DEFAULT 0,
  `recording_file_id` BIGINT       DEFAULT NULL,
  `ai_summary`        CLOB         DEFAULT NULL,
  `ai_analysis`       CLOB         DEFAULT NULL,
  `has_violation`     TINYINT      NOT NULL DEFAULT 0,
  `violation_detail`  CLOB         DEFAULT NULL,
  `follow_user_id`    BIGINT       NOT NULL,
  `follow_user_org_id` BIGINT     DEFAULT NULL,
  `created_by`        BIGINT       DEFAULT NULL,
  `created_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by`        BIGINT       DEFAULT NULL,
  `updated_time`      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted`           TINYINT      NOT NULL DEFAULT 0,
  `version`           INT          NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
);
